run:
  timeout: 5m
  tests: true
  go: "1.23"

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - gocyclo
    - gosec
    - misspell
    - revive
    - unconvert
    - goimports
    - bodyclose
    - nolintlint

linters-settings:
  gocyclo:
    min-complexity: 18
  gosec:
    excludes:
      - G104
      - G404
  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true
  staticcheck:
    checks: ["all", "-ST1000", "-ST1003"]

issues:
  exclude-dirs:
    - bin
    - terraform
    - scripts
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - gocyclo
  max-issues-per-linter: 0
  max-same-issues: 0
